### ISSUE TITLE
Build Egg Cooking Helper

### ISSUE THREAD

**Issue by Marvin-Dem** [Marvin-Dem/Egg-Cooking-Helper#1]
There shall be a small web app that does nothing but let a user set up a timer to cook an egg.

# Features

- [x] The egg size can be defined using radio buttons (S, M, L)
- [x] The preferred cooking level can be defined using radio buttons (Soft, Medium, Hard)
- [x] The cooking duration of the egg is displayed and calculated based on the the 2 information given
- [x] There is a "Start" button that starts the timer when clicked
- [x] When a timer is actively running, the button shall switch to "Stop"
- [x] The displayed time updates accordingly
- [x] When reaching 00:00 an alarm sound should be played
- [x] Stopping a timer resets the timer and stops the potentially running alarm

# ToDos

- [x] Create a wireframe based on the required features
- [x] Set up a new repo on GitHub
- [x] Set up a fresh boilerplate using Vite, React, TypeScript and Tailwind
- [x] Build all listed features
- [x] Add some design
- [x] Double check the app looks good both on mobile and desktop

**Comment by Marvin-Dem** [comment]
First Wireframe:

<img width="991" alt="Image" src="https://github.com/user-attachments/assets/812c960a-c088-43e3-b46e-41ce6762dcbc" />

**Comment by p-runge** [comment]
What's the current status of this project? Is there already a deployed version of it?
